#!/bin/bash

while (( $# > 0 ))
do
    case "$1" in
        -h | --help)
            exit 0
            ;;
        -s | --sync)
            git fetch --prune --all
            git branch --merged \
                | grep -v '*' \
                | xargs -I % git branch -d %
            exit 0
            ;;
        "")
            break
            ;;
        *)
            # If an argument is given
            git checkout -b "$1"
            exit $?
            ;;
    esac
    shift
done

branch="$(
git branch --color -a \
    | grep -v '*' \
    | sed -E 's/^ +//' \
    | fzy \
    | perl -pe 's/\e\[?.*?[\@-~]//g'
)"

if [[ -z $branch ]]; then
    exit 0
fi

is_already_branched() { git branch | grep -q "${branch##*/}" &>/dev/null; }

if [[ $branch =~ ^remotes ]]; then
    if is_already_branched; then
        # already exists
        git checkout "${branch##*/}"
        exit $?
    fi
    git checkout -b "${branch##*/}" "${branch#*/}"
else
    if is_already_branched; then
        git checkout "$branch"
    else
        git checkout -b "$branch"
    fi
fi
